import type { Metadata } from "next";
import "tailwindcss/tailwind.css";
import { Noto_Sans_Georgian } from "@next/font/google";
import "./globals.css";
import Providers from "./providers";
import { UserProvider } from "@/contexts/UserContext";

const georgian = Noto_Sans_Georgian({ subsets: ["georgian"] });

export const metadata: Metadata = {
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="light">
      <body className={georgian.className}>
        <Providers>
          <UserProvider>{children}</UserProvider>
        </Providers>
      </body>
    </html>
  );
}
